### ISSUE TITLE
header does not exist in zip

### ISSUE THREAD

**Issue by mgood7123** [HumbleUI/SkiaBuild#1]
"src/gpu/GrGpu.h" does not exist in release zip

```
src
  utils
  gpu
    gl
  core
```

**Comment by tonsky** [comment]
Try this release, I added the folder https://github.com/HumbleUI/SkiaBuild/releases/tag/m100-d5a507cafd

I wonder why during my usage this never was a problem. Are you compiling C++ with this package?

**Comment by mgood7123** [comment]
> Try this release, I added the folder https://github.com/HumbleUI/SkiaBuild/releases/tag/m100-d5a507cafd
> 
> I wonder why during my usage this never was a problem. Are you compiling C++ with this package?

yea

**Comment by mgood7123** [comment]
unfortunately there are still more

`/Users/smallville7123/StudioProjects/Astrid/app/src/main/cpp/SkiaApp/ViewSystem/SkiaBuild/Skia-m100-d5a507cafd-macos-Release-x64/src/gpu/GrShaderCaps.h:12:10: fatal error: 'src/gpu/glsl/GrGLSL.h' file not found`
`#include "src/gpu/glsl/GrGLSL.h"`
