### ISSUE TITLE
[fork] on windows (Release) "release.py" urllib.error.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by istinnstudio** [HumbleUI/SkiaBuild#3]
I have created a fork in order to build a windows (Release) with direct3d disabled.  Local build was unsuccessful, several errors, so I have forked [SkiaBuild](https://github.com/HumbleUI/SkiaBuild) in order to run the same actions as original, with 'skia_use_direct3d=false' and go on to build a new skija dll from there.
Trying to run current github actions, I get an authorization - permission error.

"release.py"
urllib.error.HTTPError: HTTP Error 401: Unauthorized
Error: Process completed with exit code 1.
##[debug]Finishing: Run python3 script/release.py --version m109-664500fa93 --build-type Release

Do we have any idea why?

**Comment by tonsky** [comment]
release.py tries to publish to maven central and you have no credentials to do that

**Comment by istinnstudio** [comment]
Ok! I see... there should be an obvious way to download the created zip file, I will check that out, but if there is a quick way to just download the zip and nothing else  that would be useful for local builds, thanks!

**Comment by tonsky** [comment]
Scroll down on the action page. I can see artifacts even in an incognito window

<img width="1624" alt="Screenshot 2022-12-19 at 00 41 06" src="https://user-images.githubusercontent.com/285292/208325624-ae4f438c-03f9-4d7e-8611-5e8a5afd447e.png">

**Comment by istinnstudio** [comment]
I have commented out @ build.yml all related bash references to release.py 
     # - shell: bash
     #   run: python3 script/release.py 
...
the action completed successfully (no errors) 
and now the created file has a download link at the action page (like the screenshot), so this issue has been resolved.. , thank you
